### ISSUE TITLE
Notustohtml does not fit quill_ delta 1.1.2

### ISSUE THREAD

**Issue by yingqiang006** [JacobWrenn/notus_to_html#4]
Notustohtml does not fit quill_ delta 1.1.2

**Comment by JacobWrenn** [comment]
Hi @yingqiang006 could you provide some more information? Notus itself doesn't seem to have support for quill_delta 1.1.2.

**Comment by JEuler** [comment]
Hi! Assuming duplicate, I can probably answer here :)
The problem is with current quill_delta (2.0.0). It is used in the Zefyr fresh version:
```
You are viewing early dev preview version of this package which is no longer actively maintained. To follow latest updates see dev releases for 1.0.0-dev.x versions. You can learn more about the upcoming 1.0.0 release here: memspace/zefyr/issues/409
```

So, I understand, that this Zefyr is dev version, but it will be the main version (as It is said in the description). 
It would be cool if you will have a look at changes for fresh `quill_delta`. I had a look and it seems that now there are changes for embed processing and also, with `data` object itself. Probably, I will help you with a conversion for the new `quill_delta` if you will need help. 

I'm using your package with current stable Zefyr, it is very cool. Thx!

**Comment by blue492** [comment]
I have same problem here
https://github.com/pulyaevskiy/quill-delta-dart/issues/19

**Comment by JacobWrenn** [comment]
Version `0.0.9-dev.1.0` is now live. It should fully support the latest zefyr quill_delta. Please open a new issue if you have any problems.
