### ISSUE TITLE
Not compatible with zefyr 1.0.0-dev.2.0

### ISSUE THREAD

**Issue by SachinTanpure** [JacobWrenn/notus_to_html#7]
Got below error when did flutter pub get

Because every version of notustohtml depends on notus ^0.1.5 and zefyr 1.0.0-dev.2.0 depends on notus ^1.0.0-dev, notustohtml is incompatible with zefyr 1.0.0-dev.2.0.

And because no versions of zefyr match >1.0.0-dev.2.0 <2.0.0, notustohtml is incompatible with zefyr ^1.0.0-dev.2.0.

So, because **** depends on both zefyr ^1.0.0-dev.2.0 and notustohtml ^0.0.8, version solving failed.
pub get failed (1; So, because **** depends on both zefyr ^1.0.0-dev.2.0 and notustohtml ^0.0.8, version solving failed.)

**Comment by priyesh-bit** [comment]
Did you find any solution?

**Comment by bruno-urgo** [comment]
Same with flutter_quill package:

Because notustohtml >=0.0.3 depends on quill_delta ^1.0.2 and flutter_quill 0.2.5 depends on quill_delta ^2.0.0, notustohtml >=0.0.3 is incompatible with flutter_quill 0.2.5.
And because no versions of flutter_quill match >0.2.5 <0.3.0, notustohtml >=0.0.3 is incompatible with flutter_quill ^0.2.5.
So, because flutter_text_editor depends on both flutter_quill ^0.2.5 and notustohtml 0.0.8, version solving failed.
pub get failed (1; So, because flutter_text_editor depends on both flutter_quill ^0.2.5 and notustohtml 0.0.8, version solving failed.)

**Comment by JacobWrenn** [comment]
Version `0.0.9-dev.1.0` is now live. It should fully support the latest zefyr quill_delta. Please open a new issue if you have any problems.
